export const villages = [
  {
    "id": "VLG-001",
    "name": "Guwahati Hill Slopes (366 sites)",
    "district": "Kamrup Metropolitan",
    "state": "Assam",
    "riskLevel": "CRITICAL",
    "hazardType": "Landslide",
    "hazardDetail": "Landslide (deforestation, unregulated hill-cutting, weak drainage)",
    "priority": "IMMEDIATE",
    "population": 7878,
    "lat": 26.1445,
    "lng": 91.7362,
    "riskScore": 80.0,
    "hazardIntensity": 0.7,
    "disasterHistory": 0.75,
    "sourceNotes": "Sentinel Assam reporting on 2026 Guwahati hills survey | Approximate location, exact geocoding pending \u2014 Guwahati representative coordinate used for the 366-site hill-slope zone."
  },
  {
    "id": "VLG-002",
    "name": "Boragaon",
    "district": "Kamrup Metropolitan",
    "state": "Assam",
    "riskLevel": "MEDIUM",
    "hazardType": "Landslide",
    "hazardDetail": "Landslide (seepage-induced, retaining wall present but failed)",
    "priority": "SHORT_TERM",
    "population": 788,
    "lat": 26.1095,
    "lng": 91.6882,
    "riskScore": 48.0,
    "hazardIntensity": 0.7,
    "disasterHistory": 0.5,
    "sourceNotes": "Ajmal IAS Academy analysis citing local reporting | Verified Boragaon locality coordinate."
  },
  {
    "id": "VLG-003",
    "name": "Jatinga-Lampur & New Harangajao (rail stations)",
    "district": "Dima Hasao",
    "state": "Assam",
    "riskLevel": "MEDIUM",
    "hazardType": "Landslide",
    "hazardDetail": "Landslide (heavy monsoon rainfall)",
    "priority": "SHORT_TERM",
    "population": 300,
    "lat": 25.169976,
    "lng": 93.015197,
    "riskScore": 42.1,
    "hazardIntensity": 0.7,
    "disasterHistory": 0.3,
    "sourceNotes": "Sentinel Assam field reporting, May 2024 | Approximate location, exact geocoding pending \u2014 Dima Hasao district headquarters (Haflong) used because the row combines Jatinga-Lampur and New Harangajao railway-station areas."
  },
  {
    "id": "VLG-004",
    "name": "Hangrum village (Mahur PS area)",
    "district": "Dima Hasao",
    "state": "Assam",
    "riskLevel": "MEDIUM",
    "hazardType": "Landslide",
    "hazardDetail": "Landslide (construction-site slope failure, heavy rainfall)",
    "priority": "SHORT_TERM",
    "population": 300,
    "lat": 25.13862,
    "lng": 93.30215,
    "riskScore": 46.1,
    "hazardIntensity": 0.7,
    "disasterHistory": 0.5,
    "sourceNotes": "Deccan Herald reporting"
  },
  {
    "id": "VLG-005",
    "name": "Haflong town area",
    "district": "Dima Hasao",
    "state": "Assam",
    "riskLevel": "HIGH",
    "hazardType": "Landslide",
    "hazardDetail": "Landslide (rainfall triggered)",
    "priority": "IMMEDIATE",
    "population": 800,
    "lat": 25.169976,
    "lng": 93.015197,
    "riskScore": 56.0,
    "hazardIntensity": 0.7,
    "disasterHistory": 0.9,
    "sourceNotes": "Multiple wire-service reports (2022 monsoon season) | Verified Haflong town coordinate."
  },
  {
    "id": "VLG-006",
    "name": "Cachar district-wide landslide/urban flood zone",
    "district": "Cachar",
    "state": "Assam",
    "riskLevel": "MEDIUM",
    "hazardType": "Flood",
    "hazardDetail": "Landslide + urban flooding",
    "priority": "SHORT_TERM",
    "population": 3000,
    "lat": 24.8333,
    "lng": 92.8,
    "riskScore": 54.4,
    "hazardIntensity": 0.7,
    "disasterHistory": 0.4,
    "sourceNotes": "ASDMA bulletin via KRC Times reporting | Approximate location, exact geocoding pending \u2014 Cachar/Silchar representative coordinate used for the district-wide zone."
  },
  {
    "id": "VLG-007",
    "name": "Bagdigi",
    "district": "Dhanbad",
    "state": "Jharkhand",
    "riskLevel": "MEDIUM",
    "hazardType": "Ground Subsidence",
    "hazardDetail": "Underground mine fire",
    "priority": "SHORT_TERM",
    "population": 790,
    "lat": 23.795653,
    "lng": 86.430386,
    "riskScore": 48.0,
    "hazardIntensity": 0.78,
    "disasterHistory": 0.3,
    "sourceNotes": "The Migration Story field reporting"
  },
  {
    "id": "VLG-008",
    "name": "Kujama",
    "district": "Dhanbad",
    "state": "Jharkhand",
    "riskLevel": "MEDIUM",
    "hazardType": "Ground Subsidence",
    "hazardDetail": "Fire + subsidence",
    "priority": "SHORT_TERM",
    "population": 790,
    "lat": 23.729634,
    "lng": 86.432346,
    "riskScore": 53.0,
    "hazardIntensity": 0.88,
    "disasterHistory": 0.3,
    "sourceNotes": "Down To Earth 'On shaky ground' field reporting"
  },
  {
    "id": "VLG-009",
    "name": "Kenduadih (Putki-Balihari Colliery area)",
    "district": "Dhanbad",
    "state": "Jharkhand",
    "riskLevel": "HIGH",
    "hazardType": "Ground Subsidence",
    "hazardDetail": "Underground fire + CO gas emission",
    "priority": "IMMEDIATE",
    "population": 790,
    "lat": 23.77574,
    "lng": 86.37609,
    "riskScore": 55.5,
    "hazardIntensity": 0.93,
    "disasterHistory": 0.3,
    "sourceNotes": "Down To Earth reporting on Dhanbad gas leak incident"
  },
  {
    "id": "VLG-010",
    "name": "Lalten Ganj",
    "district": "Dhanbad",
    "state": "Jharkhand",
    "riskLevel": "MEDIUM",
    "hazardType": "Ground Subsidence",
    "hazardDetail": "Surface fire + subsidence",
    "priority": "SHORT_TERM",
    "population": 790,
    "lat": 23.795653,
    "lng": 86.430386,
    "riskScore": 53.0,
    "hazardIntensity": 0.88,
    "disasterHistory": 0.3,
    "sourceNotes": "Down To Earth 'Reign of Fire' reporting (2025) | Approximate location, exact geocoding pending \u2014 Dhanbad district headquarters coordinate used because Lalten Ganj is a coalfield settlement without a sufficiently reliable standalone public GPS point."
  },
  {
    "id": "VLG-011",
    "name": "Lukodiya",
    "district": "Ranchi",
    "state": "Jharkhand",
    "riskLevel": "LOW",
    "hazardType": "Ground Subsidence",
    "hazardDetail": "Mining-affected land (subsidence risk potential)",
    "priority": "MEDIUM_TERM",
    "population": 343,
    "lat": 23.36868,
    "lng": 85.32486,
    "riskScore": 27.3,
    "hazardIntensity": 0.4,
    "disasterHistory": 0.3,
    "sourceNotes": "Business Jharkhand reporting (Oct 2025) | Approximate location, exact geocoding pending \u2014 Ranchi district headquarters coordinate used because the exact Lukodiya village GPS point could not be reliably verified."
  },
  {
    "id": "VLG-012",
    "name": "Kathal Badi",
    "district": "Sahibganj",
    "state": "Jharkhand",
    "riskLevel": "MEDIUM",
    "hazardType": "Flood",
    "hazardDetail": "Riverine flood (Ganga)",
    "priority": "SHORT_TERM",
    "population": 335,
    "lat": 25.23986,
    "lng": 87.63258,
    "riskScore": 42.3,
    "hazardIntensity": 0.7,
    "disasterHistory": 0.3,
    "sourceNotes": "Outlook India field reporting on Sahibganj floods | Approximate location, exact geocoding pending \u2014 Sahibganj district headquarters coordinate used because the exact Kathal Badi GPS point could not be reliably verified."
  },
  {
    "id": "VLG-013",
    "name": "East/West Bokaro Coalfield Belt",
    "district": "Bokaro / Ramgarh",
    "state": "Jharkhand",
    "riskLevel": "LOW",
    "hazardType": "Ground Subsidence",
    "hazardDetail": "Mining subsidence potential (unconfirmed habitation-level data)",
    "priority": "MEDIUM_TERM",
    "population": 1000,
    "lat": 23.6693,
    "lng": 86.1511,
    "riskScore": 29.8,
    "hazardIntensity": 0.4,
    "disasterHistory": 0.3,
    "sourceNotes": "CCL / Wikipedia coalfield pages - flag for direct CCL/JSDMA follow-up | Approximate location, exact geocoding pending \u2014 representative coordinate used for the East/West Bokaro coalfield belt spanning Bokaro/Ramgarh. | Approximate location, exact geocoding pending \u2014 Bokaro district headquarters coordinate used because the row describes the East/West Bokaro coalfield belt spanning Bokaro/Ramgarh."
  },
  {
    "id": "VLG-014",
    "name": "Chellanam",
    "district": "Ernakulam",
    "state": "Kerala",
    "riskLevel": "MEDIUM",
    "hazardType": "Storm Surge",
    "hazardDetail": "Coastal erosion + seasonal flooding",
    "priority": "SHORT_TERM",
    "population": 643,
    "lat": 9.80721,
    "lng": 76.27742,
    "riskScore": 45.9,
    "hazardIntensity": 0.75,
    "disasterHistory": 0.3,
    "sourceNotes": "The News Minute / The South First field reporting | Verified Chellanam village coordinate."
  },
  {
    "id": "VLG-015",
    "name": "Alappad",
    "district": "Kollam",
    "state": "Kerala",
    "riskLevel": "MEDIUM",
    "hazardType": "Storm Surge",
    "hazardDetail": "Coastal erosion",
    "priority": "SHORT_TERM",
    "population": 637,
    "lat": 9.06269,
    "lng": 76.49884,
    "riskScore": 45.9,
    "hazardIntensity": 0.75,
    "disasterHistory": 0.3,
    "sourceNotes": "NCCR coastal defence mapping study (Kollam district survey) | Verified Alappad village coordinate."
  },
  {
    "id": "VLG-016",
    "name": "Valiathura",
    "district": "Thiruvananthapuram",
    "state": "Kerala",
    "riskLevel": "MEDIUM",
    "hazardType": "Storm Surge",
    "hazardDetail": "Coastal erosion",
    "priority": "SHORT_TERM",
    "population": 905,
    "lat": 8.46453,
    "lng": 76.92692,
    "riskScore": 46.9,
    "hazardIntensity": 0.75,
    "disasterHistory": 0.3,
    "sourceNotes": "NCCR National Assessment of Shoreline Changes report | Verified Valiyathura locality coordinate."
  },
  {
    "id": "VLG-017",
    "name": "Poonthura",
    "district": "Thiruvananthapuram",
    "state": "Kerala",
    "riskLevel": "MEDIUM",
    "hazardType": "Storm Surge",
    "hazardDetail": "Coastal erosion",
    "priority": "SHORT_TERM",
    "population": 905,
    "lat": 8.466,
    "lng": 76.95,
    "riskScore": 46.9,
    "hazardIntensity": 0.75,
    "disasterHistory": 0.3,
    "sourceNotes": "Regional coastal-vulnerability field reporting"
  },
  {
    "id": "VLG-018",
    "name": "Anjuthengu (Anjengo)",
    "district": "Thiruvananthapuram",
    "state": "Kerala",
    "riskLevel": "MEDIUM",
    "hazardType": "Storm Surge",
    "hazardDetail": "Coastal erosion",
    "priority": "SHORT_TERM",
    "population": 905,
    "lat": 8.675045,
    "lng": 76.758644,
    "riskScore": 46.9,
    "hazardIntensity": 0.75,
    "disasterHistory": 0.3,
    "sourceNotes": "Field reporting (Medium/coastal-erosion feature) | Verified Anchuthengu/Anjuthengu town coordinate."
  },
  {
    "id": "VLG-019",
    "name": "Varkala",
    "district": "Thiruvananthapuram",
    "state": "Kerala",
    "riskLevel": "MEDIUM",
    "hazardType": "Storm Surge",
    "hazardDetail": "Coastal erosion + unstable cliff sands",
    "priority": "SHORT_TERM",
    "population": 905,
    "lat": 8.7379,
    "lng": 76.7163,
    "riskScore": 46.9,
    "hazardIntensity": 0.75,
    "disasterHistory": 0.3,
    "sourceNotes": "Field reporting (Medium/coastal-erosion feature)"
  },
  {
    "id": "VLG-020",
    "name": "Kochu Veli",
    "district": "Thiruvananthapuram",
    "state": "Kerala",
    "riskLevel": "MEDIUM",
    "hazardType": "Storm Surge",
    "hazardDetail": "Coastal erosion",
    "priority": "SHORT_TERM",
    "population": 905,
    "lat": 8.5,
    "lng": 76.9,
    "riskScore": 46.9,
    "hazardIntensity": 0.75,
    "disasterHistory": 0.3,
    "sourceNotes": "Field reporting (Medium/coastal-erosion feature)"
  },
  {
    "id": "VLG-021",
    "name": "Kozhikode Corporation coastal belt",
    "district": "Kozhikode",
    "state": "Kerala",
    "riskLevel": "HIGH",
    "hazardType": "Storm Surge",
    "hazardDetail": "Coastal erosion",
    "priority": "IMMEDIATE",
    "population": 3290,
    "lat": 11.2588,
    "lng": 75.7804,
    "riskScore": 56.0,
    "hazardIntensity": 0.75,
    "disasterHistory": 0.3,
    "sourceNotes": "ICSF / Kozhikode fishermen association reporting | Approximate location, exact geocoding pending \u2014 Kozhikode city/district representative coordinate used for the corporation coastal belt."
  },
  {
    "id": "VLG-022",
    "name": "Ponnani / Tanur coastal belt",
    "district": "Malappuram",
    "state": "Kerala",
    "riskLevel": "MEDIUM",
    "hazardType": "Storm Surge",
    "hazardDetail": "Coastal erosion",
    "priority": "SHORT_TERM",
    "population": 2892,
    "lat": 11.04212,
    "lng": 76.08039,
    "riskScore": 54.5,
    "hazardIntensity": 0.75,
    "disasterHistory": 0.3,
    "sourceNotes": "Kerala Fisheries Department success-story report | Approximate location, exact geocoding pending \u2014 Malappuram district headquarters coordinate used for the Ponnani/Tanur coastal belt."
  },
  {
    "id": "VLG-023",
    "name": "Kuttanad (below-sea-level belt)",
    "district": "Alappuzha",
    "state": "Kerala",
    "riskLevel": "HIGH",
    "hazardType": "Flood",
    "hazardDetail": "Chronic flooding (below mean sea level, distinct from erosion)",
    "priority": "IMMEDIATE",
    "population": 3760,
    "lat": 9.4981,
    "lng": 76.3326,
    "riskScore": 65.3,
    "hazardIntensity": 0.9,
    "disasterHistory": 0.3,
    "sourceNotes": "Well-documented geography of Kuttanad region | Approximate location, exact geocoding pending \u2014 Alappuzha district headquarters coordinate used for the Kuttanad belt. | Approximate location, exact geocoding pending \u2014 Alappuzha district headquarters coordinate used because Kuttanad is a broad below-sea-level belt rather than one point."
  },
  {
    "id": "VLG-024",
    "name": "Tupul / Makhuam (Marangjing camp)",
    "district": "Noney",
    "state": "Manipur",
    "riskLevel": "MEDIUM",
    "hazardType": "Landslide",
    "hazardDetail": "Landslide (rainfall triggered, compounded by unregulated hill-cutting for railway construction)",
    "priority": "SHORT_TERM",
    "population": 300,
    "lat": 24.7842,
    "lng": 93.6035,
    "riskScore": 42.1,
    "hazardIntensity": 0.7,
    "disasterHistory": 0.3,
    "sourceNotes": "Wikipedia / GSI preliminary report / Down To Earth / SANDRP investigative reporting | Approximate location, exact geocoding pending \u2014 Noney/Longmai headquarters coordinate used because the row combines Tupul/Makhuam/Marangjing."
  },
  {
    "id": "VLG-025",
    "name": "Kambiron",
    "district": "Noney",
    "state": "Manipur",
    "riskLevel": "MEDIUM",
    "hazardType": "Landslide",
    "hazardDetail": "Landslide (rainfall + slope destabilisation from railway cutting)",
    "priority": "SHORT_TERM",
    "population": 300,
    "lat": 24.727282,
    "lng": 93.372696,
    "riskScore": 42.1,
    "hazardIntensity": 0.7,
    "disasterHistory": 0.3,
    "sourceNotes": "SANDRP investigative report, July 2022 | Verified Kambiron village coordinate."
  },
  {
    "id": "VLG-026",
    "name": "Khumji",
    "district": "Noney",
    "state": "Manipur",
    "riskLevel": "MEDIUM",
    "hazardType": "Landslide",
    "hazardDetail": "Landslide (rainfall + slope destabilisation from railway cutting)",
    "priority": "SHORT_TERM",
    "population": 300,
    "lat": 24.888889,
    "lng": 93.606111,
    "riskScore": 42.1,
    "hazardIntensity": 0.7,
    "disasterHistory": 0.3,
    "sourceNotes": "SANDRP investigative report, July 2022 | Approximate location, exact geocoding pending \u2014 verified Khumji-area government-school coordinate used because a single village-centre coordinate was not available."
  },
  {
    "id": "VLG-027",
    "name": "Pongringlong",
    "district": "Noney",
    "state": "Manipur",
    "riskLevel": "MEDIUM",
    "hazardType": "Landslide",
    "hazardDetail": "Landslide (rainfall + slope destabilisation from railway cutting)",
    "priority": "SHORT_TERM",
    "population": 300,
    "lat": 24.79209,
    "lng": 93.66663,
    "riskScore": 42.1,
    "hazardIntensity": 0.7,
    "disasterHistory": 0.3,
    "sourceNotes": "SANDRP investigative report, July 2022 | Verified Pongringlong/Charoipandongba Kabui village coordinate."
  },
  {
    "id": "VLG-028",
    "name": "Jiribam-Tamenglong-Noney-Kangpokpi-Imphal West railway corridor",
    "district": "Jiribam",
    "state": "Manipur",
    "riskLevel": "LOW",
    "hazardType": "Landslide",
    "hazardDetail": "Landslide (cut-slope exposure along the alignment)",
    "priority": "MEDIUM_TERM",
    "population": 1000,
    "lat": 24.8,
    "lng": 93.12,
    "riskScore": 24.8,
    "hazardIntensity": 0.3,
    "disasterHistory": 0.3,
    "sourceNotes": "Down To Earth 'Himalayan plunder' analysis, 2024 | Approximate location, exact geocoding pending \u2014 Jiribam district-headquarters coordinate used for the multi-district railway corridor."
  },
  {
    "id": "VLG-029",
    "name": "Satabhaya",
    "district": "Kendrapara",
    "state": "Odisha",
    "riskLevel": "MEDIUM",
    "hazardType": "Cyclone",
    "hazardDetail": "Coastal erosion + cyclone storm surge",
    "priority": "SHORT_TERM",
    "population": 300,
    "lat": 20.605,
    "lng": 86.881,
    "riskScore": 44.6,
    "hazardIntensity": 0.75,
    "disasterHistory": 0.3,
    "sourceNotes": "Multiple field-reporting sources (Down To Earth, Reuters, national press) | Verified/near-site Satabhaya coastal coordinate; exact village centre varies because Satabhaya is a coastal/relocating settlement."
  },
  {
    "id": "VLG-030",
    "name": "Pentha",
    "district": "Kendrapara",
    "state": "Odisha",
    "riskLevel": "MEDIUM",
    "hazardType": "Cyclone",
    "hazardDetail": "Coastal erosion + cyclone storm surge",
    "priority": "SHORT_TERM",
    "population": 300,
    "lat": 20.543611,
    "lng": 86.788611,
    "riskScore": 44.6,
    "hazardIntensity": 0.75,
    "disasterHistory": 0.3,
    "sourceNotes": "NCCR shoreline change data + regional field reporting | Verified Pentha village coordinate from the Government of India heritage-site record."
  },
  {
    "id": "VLG-031",
    "name": "Fulapatana, Harishpur, Naharan, Marichpur, Balipatana, Dhanuhar Belari (coastal Jagatsinghpur villages)",
    "district": "Jagatsinghpur",
    "state": "Odisha",
    "riskLevel": "MEDIUM",
    "hazardType": "Cyclone",
    "hazardDetail": "Cyclone storm surge (1999 Super Cyclone-affected)",
    "priority": "SHORT_TERM",
    "population": 388,
    "lat": 20.25,
    "lng": 86.17,
    "riskScore": 42.5,
    "hazardIntensity": 0.7,
    "disasterHistory": 0.3,
    "sourceNotes": "Familypedia/Wikipedia district summary citing 1999 Super Cyclone impact | Approximate location, exact geocoding pending \u2014 Jagatsinghpur district-headquarters/representative coordinate used because the row contains multiple villages."
  },
  {
    "id": "VLG-032",
    "name": "Chooralmala (Meppadi)",
    "district": "Wayanad",
    "state": "Kerala",
    "riskLevel": "HIGH",
    "hazardType": "Landslide",
    "hazardDetail": "Debris Flow & Massive Landslide",
    "priority": "IMMEDIATE",
    "population": 1450,
    "lat": 11.5367,
    "lng": 76.1362,
    "riskScore": 71.0,
    "hazardIntensity": 0.95,
    "disasterHistory": 0.9,
    "sourceNotes": "ISRO Landslide Atlas 2023 & Kerala SDMA July 2024 disaster survey | Verified Meppadi village coordinates"
  },
  {
    "id": "VLG-033",
    "name": "Mundakkai (Meppadi)",
    "district": "Wayanad",
    "state": "Kerala",
    "riskLevel": "HIGH",
    "hazardType": "Landslide",
    "hazardDetail": "Severe Landslide & Debris Torrent",
    "priority": "IMMEDIATE",
    "population": 1200,
    "lat": 11.5431,
    "lng": 76.1558,
    "riskScore": 69.1,
    "hazardIntensity": 0.95,
    "disasterHistory": 0.85,
    "sourceNotes": "GSI / SDMA field survey on 2024 Wayanad landslide disaster | Verified GPS pin"
  },
  {
    "id": "VLG-034",
    "name": "Punchirimattam (Meppadi)",
    "district": "Wayanad",
    "state": "Kerala",
    "riskLevel": "HIGH",
    "hazardType": "Landslide",
    "hazardDetail": "High-Altitude Landslide Trigger Zone",
    "priority": "IMMEDIATE",
    "population": 450,
    "lat": 11.554,
    "lng": 76.168,
    "riskScore": 65.2,
    "hazardIntensity": 0.95,
    "disasterHistory": 0.8,
    "sourceNotes": "ISRO / GSI preliminary report on Wayanad debris-flow origin"
  },
  {
    "id": "VLG-035",
    "name": "Attamala (Meppadi)",
    "district": "Wayanad",
    "state": "Kerala",
    "riskLevel": "HIGH",
    "hazardType": "Flash Flood",
    "hazardDetail": "Slope Destabilisation & Flash Flood",
    "priority": "IMMEDIATE",
    "population": 600,
    "lat": 11.528,
    "lng": 76.142,
    "riskScore": 59.8,
    "hazardIntensity": 0.85,
    "disasterHistory": 0.75,
    "sourceNotes": "Kerala Revenue Department landslide vulnerability map 2024"
  },
  {
    "id": "VLG-036",
    "name": "Sunil Ward (Joshimath)",
    "district": "Chamoli",
    "state": "Uttarakhand",
    "riskLevel": "HIGH",
    "hazardType": "Ground Subsidence",
    "hazardDetail": "Land Subsidence & Structural Cracking",
    "priority": "IMMEDIATE",
    "population": 1800,
    "lat": 30.5574,
    "lng": 79.5678,
    "riskScore": 67.9,
    "hazardIntensity": 0.9,
    "disasterHistory": 0.8,
    "sourceNotes": "USDMA & IIT Roorkee geotechnical survey of Joshimath subsidence crisis (2023)"
  },
  {
    "id": "VLG-037",
    "name": "Manohar Bagh (Joshimath)",
    "district": "Chamoli",
    "state": "Uttarakhand",
    "riskLevel": "HIGH",
    "hazardType": "Ground Subsidence",
    "hazardDetail": "Severe Ground Fissuring & Subsidence",
    "priority": "IMMEDIATE",
    "population": 1400,
    "lat": 30.5545,
    "lng": 79.5645,
    "riskScore": 62.8,
    "hazardIntensity": 0.85,
    "disasterHistory": 0.75,
    "sourceNotes": "USDMA / CBRI structural damage index report"
  },
  {
    "id": "VLG-038",
    "name": "Singdhar Ward (Joshimath)",
    "district": "Chamoli",
    "state": "Uttarakhand",
    "riskLevel": "HIGH",
    "hazardType": "Ground Subsidence",
    "hazardDetail": "Active Land Subsidence & Slope Creep",
    "priority": "IMMEDIATE",
    "population": 1100,
    "lat": 30.552,
    "lng": 79.561,
    "riskScore": 65.2,
    "hazardIntensity": 0.9,
    "disasterHistory": 0.8,
    "sourceNotes": "IIT Roorkee / USDMA technical bulletin"
  },
  {
    "id": "VLG-039",
    "name": "Raini Village",
    "district": "Chamoli",
    "state": "Uttarakhand",
    "riskLevel": "HIGH",
    "hazardType": "Flash Flood",
    "hazardDetail": "Glacial Lake Outburst (GLOF) & Flash Flood",
    "priority": "IMMEDIATE",
    "population": 650,
    "lat": 30.4858,
    "lng": 79.7125,
    "riskScore": 68.0,
    "hazardIntensity": 0.95,
    "disasterHistory": 0.9,
    "sourceNotes": "Wadia Institute of Himalayan Geology & GSI 2021 Chamoli disaster report"
  },
  {
    "id": "VLG-040",
    "name": "Tapovan",
    "district": "Chamoli",
    "state": "Uttarakhand",
    "riskLevel": "HIGH",
    "hazardType": "Flash Flood",
    "hazardDetail": "Flash Flood & Debris Torrent",
    "priority": "IMMEDIATE",
    "population": 850,
    "lat": 30.493,
    "lng": 79.6275,
    "riskScore": 62.7,
    "hazardIntensity": 0.85,
    "disasterHistory": 0.85,
    "sourceNotes": "NDRF / USDMA flash flood zone survey"
  },
  {
    "id": "VLG-041",
    "name": "Ghoramara Island",
    "district": "South 24 Parganas",
    "state": "West Bengal",
    "riskLevel": "CRITICAL",
    "hazardType": "Storm Surge",
    "hazardDetail": "Severe Coastal Erosion & Sea Level Rise",
    "priority": "IMMEDIATE",
    "population": 4500,
    "lat": 21.9167,
    "lng": 88.1333,
    "riskScore": 82.6,
    "hazardIntensity": 0.95,
    "disasterHistory": 0.9,
    "sourceNotes": "School of Oceanographic Studies, Jadavpur University & NCCR shoreline assessment"
  },
  {
    "id": "VLG-042",
    "name": "Mousuni Island",
    "district": "South 24 Parganas",
    "state": "West Bengal",
    "riskLevel": "CRITICAL",
    "hazardType": "Storm Surge",
    "hazardDetail": "Embankment Breach & Tidal Inundation",
    "priority": "IMMEDIATE",
    "population": 5200,
    "lat": 21.5667,
    "lng": 88.2333,
    "riskScore": 81.8,
    "hazardIntensity": 0.9,
    "disasterHistory": 0.85,
    "sourceNotes": "WBDMD / WWF Sundarbans climate vulnerability assessment"
  },
  {
    "id": "VLG-043",
    "name": "Sagar Island (South Coastal Belt)",
    "district": "South 24 Parganas",
    "state": "West Bengal",
    "riskLevel": "CRITICAL",
    "hazardType": "Cyclone",
    "hazardDetail": "Cyclone Storm Surge & Inundation",
    "priority": "IMMEDIATE",
    "population": 6500,
    "lat": 21.65,
    "lng": 88.0833,
    "riskScore": 84.3,
    "hazardIntensity": 0.85,
    "disasterHistory": 0.85,
    "sourceNotes": "West Bengal Disaster Management Department bulletin (Post-Amphan/Yaas)"
  },
  {
    "id": "VLG-044",
    "name": "Manikaran Valley",
    "district": "Kullu",
    "state": "Himachal Pradesh",
    "riskLevel": "HIGH",
    "hazardType": "Flash Flood",
    "hazardDetail": "Parvati River Flash Flood & Riverbank Erosion",
    "priority": "IMMEDIATE",
    "population": 2200,
    "lat": 32.027,
    "lng": 77.348,
    "riskScore": 65.9,
    "hazardIntensity": 0.85,
    "disasterHistory": 0.75,
    "sourceNotes": "HPSDMA Monsoon 2023 disaster damage evaluation report"
  },
  {
    "id": "VLG-045",
    "name": "Thunag",
    "district": "Mandi",
    "state": "Himachal Pradesh",
    "riskLevel": "HIGH",
    "hazardType": "Flash Flood",
    "hazardDetail": "Cloudburst & Severe Debris Torrent",
    "priority": "IMMEDIATE",
    "population": 1600,
    "lat": 31.545,
    "lng": 77.165,
    "riskScore": 67.1,
    "hazardIntensity": 0.9,
    "disasterHistory": 0.8,
    "sourceNotes": "HPSDMA & Mandi DDMA field survey on 2023 cloudburst disaster"
  },
  {
    "id": "VLG-046",
    "name": "Pandoh Valley",
    "district": "Mandi",
    "state": "Himachal Pradesh",
    "riskLevel": "HIGH",
    "hazardType": "Flood",
    "hazardDetail": "Beas River Flood Inundation & Slope Failure",
    "priority": "IMMEDIATE",
    "population": 1900,
    "lat": 31.669,
    "lng": 77.018,
    "riskScore": 65.7,
    "hazardIntensity": 0.85,
    "disasterHistory": 0.8,
    "sourceNotes": "HPSDMA Beas river basin vulnerability assessment"
  },
  {
    "id": "VLG-047",
    "name": "Salmora (Majuli Island)",
    "district": "Majuli",
    "state": "Assam",
    "riskLevel": "CRITICAL",
    "hazardType": "Flood",
    "hazardDetail": "Severe Brahmaputra Riverbank Erosion",
    "priority": "IMMEDIATE",
    "population": 3200,
    "lat": 26.85,
    "lng": 94.2,
    "riskScore": 75.2,
    "hazardIntensity": 0.9,
    "disasterHistory": 0.9,
    "sourceNotes": "Brahmaputra Board & ASDMA Majuli erosion mitigation report"
  },
  {
    "id": "VLG-048",
    "name": "Jiadhall River Basin (Dhemaji)",
    "district": "Dhemaji",
    "state": "Assam",
    "riskLevel": "HIGH",
    "hazardType": "Flash Flood",
    "hazardDetail": "Chronic Sand Deposition & Flash Flood",
    "priority": "IMMEDIATE",
    "population": 2800,
    "lat": 27.4833,
    "lng": 94.5833,
    "riskScore": 70.2,
    "hazardIntensity": 0.85,
    "disasterHistory": 0.85,
    "sourceNotes": "ASDMA Dhemaji flood vulnerability atlas"
  },
  {
    "id": "VLG-049",
    "name": "Longmai Village (Noney)",
    "district": "Noney",
    "state": "Manipur",
    "riskLevel": "HIGH",
    "hazardType": "Landslide",
    "hazardDetail": "Railway Cut-Slope Failure & Landslide",
    "priority": "IMMEDIATE",
    "population": 1100,
    "lat": 24.78,
    "lng": 93.61,
    "riskScore": 58.2,
    "hazardIntensity": 0.8,
    "disasterHistory": 0.7,
    "sourceNotes": "SANDRP investigative report / Manipur SDMA"
  },
  {
    "id": "VLG-050",
    "name": "Tamenglong Town Slope",
    "district": "Tamenglong",
    "state": "Manipur",
    "riskLevel": "HIGH",
    "hazardType": "Landslide",
    "hazardDetail": "Hill-Slope Mudslide & Water Seepage",
    "priority": "IMMEDIATE",
    "population": 1600,
    "lat": 24.985,
    "lng": 93.492,
    "riskScore": 59.1,
    "hazardIntensity": 0.8,
    "disasterHistory": 0.65,
    "sourceNotes": "Manipur SDMA hazard mapping report"
  },
  {
    "id": "VLG-051",
    "name": "Gaurikund Base Camp",
    "district": "Rudraprayag",
    "state": "Uttarakhand",
    "riskLevel": "HIGH",
    "hazardType": "Flash Flood",
    "hazardDetail": "Mandakini Flash Flood & Severe Debris Flow",
    "priority": "IMMEDIATE",
    "population": 1200,
    "lat": 30.65,
    "lng": 79.0167,
    "riskScore": 71.1,
    "hazardIntensity": 0.95,
    "disasterHistory": 0.95,
    "sourceNotes": "NDMA 2013 Kedarnath Post-Disaster Needs Assessment (PDNA) & USDMA survey"
  },
  {
    "id": "VLG-052",
    "name": "Sonprayag River Confluence",
    "district": "Rudraprayag",
    "state": "Uttarakhand",
    "riskLevel": "HIGH",
    "hazardType": "Flash Flood",
    "hazardDetail": "Riverbank Collapse & Flash Flood",
    "priority": "IMMEDIATE",
    "population": 850,
    "lat": 30.63,
    "lng": 78.998,
    "riskScore": 66.2,
    "hazardIntensity": 0.9,
    "disasterHistory": 0.9,
    "sourceNotes": "USDMA Rudraprayag flood hazard map 2013"
  },
  {
    "id": "VLG-053",
    "name": "Rajbagh Ward (Srinagar)",
    "district": "Srinagar",
    "state": "Jammu and Kashmir",
    "riskLevel": "CRITICAL",
    "hazardType": "Flood",
    "hazardDetail": "Catastrophic Jhelum River Inundation",
    "priority": "IMMEDIATE",
    "population": 4800,
    "lat": 34.07,
    "lng": 74.82,
    "riskScore": 80.3,
    "hazardIntensity": 0.9,
    "disasterHistory": 0.85,
    "sourceNotes": "J&K SDMA & CWC Sept 2014 Flood Inundation Atlas (18-ft peak submersion)"
  },
  {
    "id": "VLG-054",
    "name": "Shivpora Lowland (Srinagar)",
    "district": "Srinagar",
    "state": "Jammu and Kashmir",
    "riskLevel": "HIGH",
    "hazardType": "Flood",
    "hazardDetail": "Bund Breach & Urban Waterlogging",
    "priority": "IMMEDIATE",
    "population": 3600,
    "lat": 34.062,
    "lng": 74.845,
    "riskScore": 72.2,
    "hazardIntensity": 0.85,
    "disasterHistory": 0.8,
    "sourceNotes": "Irrigation and Flood Control Department J&K report 2014"
  },
  {
    "id": "VLG-055",
    "name": "Anantnag Old Town Belt",
    "district": "Anantnag",
    "state": "Jammu and Kashmir",
    "riskLevel": "CRITICAL",
    "hazardType": "Flash Flood",
    "hazardDetail": "Upper Jhelum Tributary Flash Flood",
    "priority": "IMMEDIATE",
    "population": 5200,
    "lat": 33.731,
    "lng": 75.152,
    "riskScore": 78.3,
    "hazardIntensity": 0.85,
    "disasterHistory": 0.8,
    "sourceNotes": "J&K SDMA district disaster management plan Anantnag"
  },
  {
    "id": "VLG-056",
    "name": "Mudichur Suburb",
    "district": "Chengalpattu",
    "state": "Tamil Nadu",
    "riskLevel": "CRITICAL",
    "hazardType": "Flood",
    "hazardDetail": "Adyar Basin Reservoir Overflow & Severe Flooding",
    "priority": "IMMEDIATE",
    "population": 5800,
    "lat": 12.909,
    "lng": 80.091,
    "riskScore": 85.1,
    "hazardIntensity": 0.9,
    "disasterHistory": 0.9,
    "sourceNotes": "TNDMA & CAG 2015 Chennai Flood Performance Audit"
  },
  {
    "id": "VLG-057",
    "name": "Velachery Lowland Marsh Basin",
    "district": "Chennai",
    "state": "Tamil Nadu",
    "riskLevel": "CRITICAL",
    "hazardType": "Flood",
    "hazardDetail": "Pallikaranai Wetland Backflow & Urban Flood",
    "priority": "IMMEDIATE",
    "population": 7200,
    "lat": 12.98,
    "lng": 80.2222,
    "riskScore": 86.9,
    "hazardIntensity": 0.85,
    "disasterHistory": 0.85,
    "sourceNotes": "Greater Chennai Corporation (GCC) flood vulnerability zonation"
  },
  {
    "id": "VLG-058",
    "name": "Tambaram West Flood Basin",
    "district": "Chengalpattu",
    "state": "Tamil Nadu",
    "riskLevel": "CRITICAL",
    "hazardType": "Flood",
    "hazardDetail": "Chembarambakkam Canal Overflow",
    "priority": "IMMEDIATE",
    "population": 4600,
    "lat": 12.924,
    "lng": 80.1278,
    "riskScore": 76.0,
    "hazardIntensity": 0.85,
    "disasterHistory": 0.8,
    "sourceNotes": "TNDMA South Chennai Flood Management Report"
  },
  {
    "id": "VLG-059",
    "name": "Satapada Coastal Habitation",
    "district": "Puri",
    "state": "Odisha",
    "riskLevel": "CRITICAL",
    "hazardType": "Cyclone",
    "hazardDetail": "Category-5 Cyclone Landfall & 200kmph Wind Surge",
    "priority": "IMMEDIATE",
    "population": 3400,
    "lat": 19.67,
    "lng": 85.43,
    "riskScore": 79.4,
    "hazardIntensity": 0.95,
    "disasterHistory": 0.95,
    "sourceNotes": "OSDMA / World Bank Damage, Loss and Needs Assessment (DLNA) for Cyclone Fani"
  },
  {
    "id": "VLG-060",
    "name": "Konark Coastal Belt",
    "district": "Puri",
    "state": "Odisha",
    "riskLevel": "CRITICAL",
    "hazardType": "Cyclone",
    "hazardDetail": "Cyclone Storm Surge & Saltwater Inundation",
    "priority": "IMMEDIATE",
    "population": 4100,
    "lat": 19.8875,
    "lng": 86.0947,
    "riskScore": 78.6,
    "hazardIntensity": 0.9,
    "disasterHistory": 0.9,
    "sourceNotes": "OSDMA Multi-Hazard Vulnerability Atlas"
  },
  {
    "id": "VLG-061",
    "name": "Malin Habitation (Ambegaon)",
    "district": "Pune",
    "state": "Maharashtra",
    "riskLevel": "HIGH",
    "hazardType": "Landslide",
    "hazardDetail": "Catastrophic Slope Collapse & Mudflow",
    "priority": "IMMEDIATE",
    "population": 750,
    "lat": 19.16,
    "lng": 73.69,
    "riskScore": 69.4,
    "hazardIntensity": 0.95,
    "disasterHistory": 0.95,
    "sourceNotes": "GSI 2014 Malin Disaster Geotechnical Investigation (151 casualties)"
  },
  {
    "id": "VLG-062",
    "name": "Taliye Village (Mahad)",
    "district": "Raigad",
    "state": "Maharashtra",
    "riskLevel": "HIGH",
    "hazardType": "Landslide",
    "hazardDetail": "Western Ghats Heavy Rainfall Landslide",
    "priority": "IMMEDIATE",
    "population": 680,
    "lat": 18.01,
    "lng": 73.49,
    "riskScore": 68.1,
    "hazardIntensity": 0.95,
    "disasterHistory": 0.9,
    "sourceNotes": "Maharashtra SDMA July 2021 Monsoon Disaster Bulletin"
  },
  {
    "id": "VLG-063",
    "name": "Irshalwadi Tribal Settlement",
    "district": "Raigad",
    "state": "Maharashtra",
    "riskLevel": "HIGH",
    "hazardType": "Landslide",
    "hazardDetail": "Hilltop Debris Flow & Cliff Collapse",
    "priority": "IMMEDIATE",
    "population": 420,
    "lat": 18.91,
    "lng": 73.23,
    "riskScore": 66.1,
    "hazardIntensity": 0.95,
    "disasterHistory": 0.85,
    "sourceNotes": "GSI / Raigad District Administration July 2023 survey"
  },
  {
    "id": "VLG-064",
    "name": "Nirmali Embankment Belt",
    "district": "Supaul",
    "state": "Bihar",
    "riskLevel": "CRITICAL",
    "hazardType": "Flood",
    "hazardDetail": "Kosi River Embankment Breach & Silt Inundation",
    "priority": "IMMEDIATE",
    "population": 6200,
    "lat": 26.31,
    "lng": 86.6,
    "riskScore": 87.6,
    "hazardIntensity": 0.9,
    "disasterHistory": 0.95,
    "sourceNotes": "Bihar Disaster Management Department & Water Resources Department annual report"
  },
  {
    "id": "VLG-065",
    "name": "Mahishi Riverine Lowlands",
    "district": "Saharsa",
    "state": "Bihar",
    "riskLevel": "CRITICAL",
    "hazardType": "Flood",
    "hazardDetail": "Chronic Monsoon Flood & Waterlogging (Chaur area)",
    "priority": "IMMEDIATE",
    "population": 5400,
    "lat": 25.88,
    "lng": 86.45,
    "riskScore": 81.1,
    "hazardIntensity": 0.85,
    "disasterHistory": 0.9,
    "sourceNotes": "BSDMA Kosi Basin Hazard Vulnerability Profile"
  },
  {
    "id": "VLG-066",
    "name": "Chungthang Valley Habitation",
    "district": "Mangan",
    "state": "Sikkim",
    "riskLevel": "HIGH",
    "hazardType": "Flash Flood",
    "hazardDetail": "Glacial Lake Outburst Flood (GLOF) & Dam Breach",
    "priority": "IMMEDIATE",
    "population": 1500,
    "lat": 27.6,
    "lng": 88.65,
    "riskScore": 71.2,
    "hazardIntensity": 0.95,
    "disasterHistory": 0.9,
    "sourceNotes": "ISRO NRSC & Sikkim SDMA Oct 2023 GLOF Damage Assessment Report"
  },
  {
    "id": "VLG-067",
    "name": "Singtam Lowland Belt",
    "district": "Gangtok",
    "state": "Sikkim",
    "riskLevel": "HIGH",
    "hazardType": "Flash Flood",
    "hazardDetail": "Teesta River Flash Flood Submersion",
    "priority": "IMMEDIATE",
    "population": 2400,
    "lat": 27.23,
    "lng": 88.49,
    "riskScore": 71.1,
    "hazardIntensity": 0.9,
    "disasterHistory": 0.85,
    "sourceNotes": "Sikkim Disaster Management Authority field bulletin"
  },
  {
    "id": "VLG-068",
    "name": "Jafarabad Coastal Settlement",
    "district": "Amreli",
    "state": "Gujarat",
    "riskLevel": "CRITICAL",
    "hazardType": "Cyclone",
    "hazardDetail": "Category-4 Cyclone Tauktae Landfall & Storm Inundation",
    "priority": "IMMEDIATE",
    "population": 4200,
    "lat": 20.87,
    "lng": 71.37,
    "riskScore": 78.0,
    "hazardIntensity": 0.9,
    "disasterHistory": 0.85,
    "sourceNotes": "GSDMA & IMD Post-Cyclone Tauktae Report (185 kmph landfall)"
  },
  {
    "id": "VLG-069",
    "name": "Mandvi Port Coastal Belt",
    "district": "Kutch",
    "state": "Gujarat",
    "riskLevel": "CRITICAL",
    "hazardType": "Cyclone",
    "hazardDetail": "Extremely Severe Cyclone Biparjoy Coastal Surge",
    "priority": "IMMEDIATE",
    "population": 5100,
    "lat": 22.83,
    "lng": 69.35,
    "riskScore": 81.4,
    "hazardIntensity": 0.9,
    "disasterHistory": 0.85,
    "sourceNotes": "GSDMA Kutch Coastal Vulnerability Assessment 2023"
  },
  {
    "id": "VLG-070",
    "name": "Ajit Singh Nagar (Vijayawada)",
    "district": "NTR",
    "state": "Andhra Pradesh",
    "riskLevel": "CRITICAL",
    "hazardType": "Flood",
    "hazardDetail": "Budameru Rivulet Breaching & 12-ft Flood Inundation",
    "priority": "IMMEDIATE",
    "population": 7600,
    "lat": 16.54,
    "lng": 80.64,
    "riskScore": 90.9,
    "hazardIntensity": 0.9,
    "disasterHistory": 0.85,
    "sourceNotes": "APSDMA Sept 2024 Vijayawada Flood Situation Report (3.5 lakh displaced)"
  },
  {
    "id": "VLG-071",
    "name": "Bapatla Lowland Coastal Belt",
    "district": "Bapatla",
    "state": "Andhra Pradesh",
    "riskLevel": "HIGH",
    "hazardType": "Cyclone",
    "hazardDetail": "Cyclone Storm Surge & Tidal Flooding",
    "priority": "IMMEDIATE",
    "population": 3800,
    "lat": 15.9,
    "lng": 80.47,
    "riskScore": 74.0,
    "hazardIntensity": 0.85,
    "disasterHistory": 0.85,
    "sourceNotes": "APSDMA Coastal Hazard Mitigation Project"
  },
  {
    "id": "VLG-072",
    "name": "Prayagraj Sangam Flood Lowlands (Bagambari/Chhota Baghada)",
    "district": "Prayagraj",
    "state": "Uttar Pradesh",
    "riskLevel": "CRITICAL",
    "hazardType": "Flood",
    "hazardDetail": "Ganga-Yamuna River Flood Inundation & Embankment Breach",
    "priority": "IMMEDIATE",
    "population": 6800,
    "lat": 25.4358,
    "lng": 81.8463,
    "riskScore": 94.9,
    "hazardIntensity": 0.92,
    "disasterHistory": 0.9,
    "sourceNotes": "UP State Disaster Management Authority (UPSDMA) Flood Vulnerability Map 2024"
  },
  {
    "id": "VLG-073",
    "name": "Dabra & Gwalior Chambal River Basin",
    "district": "Gwalior",
    "state": "Madhya Pradesh",
    "riskLevel": "CRITICAL",
    "hazardType": "Flash Flood",
    "hazardDetail": "Extreme Flash Flood & River Overflow Inundation",
    "priority": "IMMEDIATE",
    "population": 5200,
    "lat": 25.9,
    "lng": 78.33,
    "riskScore": 84.9,
    "hazardIntensity": 0.95,
    "disasterHistory": 0.88,
    "sourceNotes": "Google Flood Hub & MPSDMA River Inundation Alert 2026"
  },
  {
    "id": "VLG-074",
    "name": "Barpeta Town & Kazi Nazrul Ghat Basin",
    "district": "Barpeta",
    "state": "Assam",
    "riskLevel": "CRITICAL",
    "hazardType": "Flood",
    "hazardDetail": "Brahmaputra Major Tributary River Flood & Severe Inundation",
    "priority": "IMMEDIATE",
    "population": 5900,
    "lat": 26.32,
    "lng": 91.0,
    "riskScore": 87.9,
    "hazardIntensity": 0.94,
    "disasterHistory": 0.92,
    "sourceNotes": "ASDMA Assam State Flood Bulletin 2026 (Active Inundation)"
  }
];
